#---------------------------------------------------------
#                ОПИСАНИЯ КВЕСТОВ В PIP-BOY
# (каждый новый раздел начинать с 100 и кратных ему чисел)
#---------------------------------------------------------



#---------------------------------------------------------
# Vault 8
#---------------------------------------------------------

{100}{}{Retrieve the device that have been stolen by the biker}
{101}{}{Pursue the kidnappers of the Overseer}
{102}{}{Fulfill your mission in the government vault}
{103}{}{}
{104}{}{}
{105}{}{Complete the special warehouse assignment}
{106}{}{Bring Sam a porn magazine}
{107}{}{Find the missing robot-scout}
{108}{}{Decipher deputy Sherriff’s disk}
{109}{}{Learn more about Gerlach community}
{110}{}{Destroy Gerlach community}
{111}{}{Spy on a "suspicious citizens" couple}
{112}{}{Collect for doctor Willmuth blood samples of pigrats , coyotes and geckos}

{120}{}{Get up on feet: talk to Graves, Willmuth, take your gear from the warehouse}
{121}{}{Biker chase: learn more about Jay in Black Rock}
{122}{}{Biker chase: learn more about Jay in New Reno}
{123}{}{Biker chase: contact the bikers}
{124}{}{Biker chase: receive a massage in Hawthorne}
{125}{}{Biker chase: find Jay in Hawthorne}
{126}{}{Get a signal jammer in Hawthorne}
{127}{}{Get rid of the tracker inside your Pip-Boy}
{128}{}{Expose doctor Willmuth}
{129}{}{Find information about project Vault 8 at Area 51}
{130}{}{}
{131}{}{}
{132}{}{}
{133}{}{}
{134}{}{Discover the true purpose of Vault 8}
{135}{}{Blow up the government vault}

#---------------------------------------------------------
# Wind of War
#---------------------------------------------------------

{200}{}{Deal with the local hooligans that attacked you}
{201}{}{The intendant has ordered 30 bottles of beer}
{202}{}{Help the prisoner escape}
{203}{}{Robert and Jessica want to escape from the settlement}
{204}{}{Find memorial information in Hawthorne}
{205}{}{Punish the soldiers, that beat the caravan}
{206}{}{Find survivors from the band of "Speed Hawk" caravan"}
{207}{}{Copy data about radio frequencies for the spy or tell about him to the military}
{208}{}{Investigate the incident at the post and report to Wesker}
{209}{}{Regain the trust of the farmer}

#---------------------------------------------------------
# Gerlach
#---------------------------------------------------------

{300}{}{Fix the water pump}
{301}{}{Save Steve from execution}
{302}{}{Move to Vault City}
{303}{}{Gecko hunting: the trial}
{304}{}{Gecko hunting: egg collection}
{305}{}{Hunt the Legend-Scorpion}

#---------------------------------------------------------
# Black Rock
#---------------------------------------------------------

{306}{}{Save the community from the "infection"}
{307}{}{Deal with escaped slaves}
{308}{}{Investigate the disappearance of brahmin}
{309}{}{Investigate the disappearance of the mail man}

#---------------------------------------------------------
# Lovelock
#---------------------------------------------------------

{400}{}{Destroy the raiders, that terrorize the tribe of Cheyenne}
{401}{}{Neutralize Big Louie}
{402}{}{Win Makozid in a fistfight}
{403}{}{Ogima requests to fix the water tank of the tribe}
{404}{}{Clear plantation of carnivorous plants}
{405}{}{"Help" Rot}
{406}{}{Return to Niskigvan his belongings taken away by a raider named Fury}
{407}{}{Akabidab asks to find Gizhiyash in New Reno}
{408}{}{Find a way to cure poor Makkon}

{410}{}{Louie: Find a way to get in Hawthorne base}
{411}{}{Louie: Collect and bring the tribute from Striker}
{412}{}{Louie: Kill the traitor named Balder}
{413}{}{Louie: Take revenge on drug dealer Solomon in Reno}
{414}{}{Louie: Stop the courier from Vegas}
{415}{}{Louie: Orginize the show in Vegas}

#---------------------------------------------------------
# Помощь при нажатии F1
#---------------------------------------------------------

{500}{}{[ИГРА]}
{501}{}{- Уменьшить яркость}
{502}{}{+ Увеличить яркость}
{503}{}{F1 Помощь}
{504}{}{F2 Уменьшить громкость}
{505}{}{F3 Увеличить громкость}
{506}{}{F4 Сохранить игру}
{507}{}{F5 Загрузить игру}
{508}{}{F6 Быстрое сохранение}
{509}{}{F7 Быстрая загрузка}
{510}{}{F10 Завершить игру}
{511}{}{F12 Сделать скриншот}
{512}{}{Ctrl+P Пауза}
{513}{}{Ctrl+R Тест. режим в гл.меню}

{514}{}{[ИНТЕРФЕЙС]}
{515}{}{М/ПКМ Смена курсора}
{516}{}{О/Esc Настройки}
{517}{}{P Pip-Boy}
{518}{}{Z Часы в Pip-Boy}
{519}{}{I Рюкзак}
{520}{}{Tab Карта местности}

{521}{}{[ДЕЙСТВИЯ]}
{522}{}{A Начать бой}
{523}{}{Space Закончить ход в бою}
{524}{}{Enter Закончить бой}
{525}{}{B Переключить предмет}
{526}{}{N Сменить режим предмета}
{527}{}{< Повернуться по ЧС}
{528}{}{> Повернуться против ЧС}
{529}{}{Home Центрировать экран на герое}

{530}{}{[НАВЫКИ]}
{531}{}{S панель навыков}
{532}{}{1 Скрытность}
{533}{}{2 Взлом}
{534}{}{3 Кража}
{535}{}{4 Диверсия}
{536}{}{5 Первая помощь}
{537}{}{6 Доктор}
{538}{}{7 Эрудиция}
{539}{}{8 Ремонт}

#---------------------------------------------------------
# NPP Poseidon Oil
#---------------------------------------------------------

{600}{}{}

#---------------------------------------------------------
# Ailey settlement
#---------------------------------------------------------

{700}{}{}

#---------------------------------------------------------
# New Reno
#---------------------------------------------------------

{800}{}{Patrick asks to cure Itch}
{801}{}{Patrick asks to return the message}
{802}{}{Patrick needs help in the organization of film exhibition}
{803}{}{Assist Harding in his sufferings}
{804}{}{Deal with the debt of Mrs. Clover}
{805}{}{Find the missing prospectors from the slums}
{806}{}{Find and punish graffiti master}
{807}{}{Find and kill, Ted Bundy}
{808}{}{Solve the mystery of photos of Ted Bundy}
{809}{}{Punish pretenders bikers}
{810}{}{Find the source of bad rumors about bikers}
{811}{}{Become a champion, a legend of New Reno ring}
{812}{}{Become a star in New Reno}
{813}{}{Execute the dirty task of Solomon}
{814}{}{Deliver a comedian from Vegas to "Cotton"}
{815}{}{Meet N. Hauer at "Silver" hotel}
{816}{}{Arrange the escape of the Devero family from the city}
{817}{}{Install bugs at "Eldorado" casino}
{818}{}{Get the data about the supply of food}

{820}{}{Wright: explore the situation in Uranium City}
{821}{}{Wright: fulfill the contract and deliver C-4}
{822}{}{Wright: recapture the mine from competitors}
{823}{}{Wright: hunt down a strange guy in the slums}
{824}{}{Wright: hold a meeting with Oliver Luciano}
{825}{}{Bertolini: meet with the informant at the ranch}
{826}{}{Bertolini: embroil the restaurant with the ranch}
{827}{}{Bertolini: destroy Luciano without killing him}
{828}{}{Bertolini: offer assistance to Luciano}
{829}{}{Bertolini: follow Huey}
{830}{}{Luciano: help Johnny Chase}
{831}{}{Luciano: frame casino "Eldorado"}
{832}{}{Luciano: frame  casino "Eldorado" (2)}
{833}{}{Luciano: steal a briefcase with money from Bertolini}
{834}{}{Luciano: provoke a conflict between gangsters}
{835}{}{Luciano: make a secret deal on the outskirts of the city}
{836}{}{Stryker: eliminate the Mormon Patrick}
{837}{}{Stryker: take the chemicals from the dealer}
{838}{}{Stryker: gather intelligence in the headquarters of Thompson}
{839}{}{Stryker: eliminate Bettie Page}
{840}{}{Stryker: prepare for the invasion to Thompson}
{841}{}{Thompson: punish street thugs}
{842}{}{Thompson: investigate the attack on the propaganda team}
{843}{}{Thompson: persuade Mordino to cooperate}
{844}{}{Thompson: sabotage Striker's deal}
{845}{}{Thompson: prepare for the invasion of the Striker}

#---------------------------------------------------------
# Bridgeport
#---------------------------------------------------------

{900}{}{Help Dante to be tested (needs gun and painkillers)}
{901}{}{Convince Dante to join the ranks of bikers}
{902}{}{Return the brahmin to the corral}
{903}{}{Cure the child on your own or bring medical supplies}
{904}{}{Equip a caravan from Reno to Bridgeport}
{905}{}{Find the missing resident}
{906}{}{Bring back electricity}
{907}{}{Save the village from bikers}
{908}{}{}
{909}{}{}

#---------------------------------------------------------
# Vegas
#---------------------------------------------------------

{1100}{}{Investigate the latest crimes in the city by the order of the mayor}
{1101}{}{Find the missing archivist's daughter}
{1102}{}{Sam Phillips is accused of spreading poison}
{1103}{}{Help the police send Sam Phillips to prison}
{1104}{}{Find an excuse for geeks}
{1105}{}{Encourage the expulsion of geeks}
{1106}{}{Unnoticed plant drugs in the geek hotel}
{1107}{}{Get Bob Neal's personal gun for Wallis}
{1108}{}{Bob Neal made a counter offer}
{1109}{}{Solve the working problem at the Hoover Dam}
{1110}{}{Investigate the attack on the Speed Hawk caravan}
{1111}{}{Help the slaves to escape from the pen}
{1112}{}{Snitch the Black Caravan to the police}
{1113}{}{Help the police in the raid on the geek lair}
{1114}{}{Become the legendary champion in Vegas}
{1115}{}{Get into the drug lab in Vegas}
{1116}{}{Erik asks to get his brother out of bondage}
{1117}{}{Pizza delivery: casino, shop and ring}
{1118}{}{Deal with the debt of Kevin the thief}
{1119}{}{Orris proposes to deal with Murphy's problem}

#---------------------------------------------------------
# Salt Lake
#---------------------------------------------------------

{1500}{}{Fix the on board computer in the train}
{1501}{}{Machinist is needed for train operation}
{1502}{}{Artesian tower needs water filter}
{1503}{}{Case of missing dog}
{1504}{}{Deal with Mark's problem}
{1505}{}{Execute the "robbery of the century in Salt Lake}
{1506}{}{Help the poor with a job}
{1507}{}{Get license for selling nuka-cola}
{1508}{}{Make a diversion on nuka-cola plant}
{1509}{}{Nuka cola: deal with "Cotton club"}
{1510}{}{Nuka cola: deal with "Silver" restaurant}
{1511}{}{Nuka cola: deal with cafe "Hard Rock"}
{1512}{}{Nuka cola: deal with the Wind of War}
{1513}{}{Fix nuka-cola factory}
{1514}{}{"Deal" with nuka-cola merchant}
{1515}{}{Punish Gary Gilmore}
{1516}{}{Slaughter Provo population}
{1517}{}{Kill Salt Lake sheriff for Provo}
{1518}{}{Return the keys to nuka-cola factory}
{1519}{}{By any means take the encoder from the caravan driver}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1600}{}{}

#---------------------------------------------------------
# Government Vault
#---------------------------------------------------------

{1700}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1800}{}{}

#---------------------------------------------------------
# Uranium City
#---------------------------------------------------------

{1900}{}{Get rid of mutants in Uranium City}
{1901}{}{Change the mine owner}
{1902}{}{Return the workers in Uranium City: administrator}
{1903}{}{Return the workers in Uranium City: machine operator}
{1904}{}{Return the workers in Uranium City: supplier}
{1905}{}{Return the workers in Uranium City: girl for the cabaret}
{1906}{}{Courier delivery of Louis Birch report}
{1907}{}{Become a sheriff}
{1908}{}{Carl asks to find a fuse}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2100}{}{}

#---------------------------------------------------------
# Car outta Gas Quests
#---------------------------------------------------------

{2200}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2300}{}{}

#---------------------------------------------------------
# Provo
#---------------------------------------------------------

{2400}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2500}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2600}{}{}

#---------------------------------------------------------
# Desert Encounter Quests
{2700}{}{}

# Mountain Encounter Quests
{2800}{}{}

# Ruined City Encounter Quests
{2900}{}{}

# Coast Encounter Quests
{3000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------
{3200}{}{}

#---------------------------------------------------------
# Car
#---------------------------------------------------------

{3300}{}{Get your own car}
{3301}{}{Improve the pickup with the help of "Chryslus Motors"}
{3302}{}{Repaint the body}
{3303}{}{Expand and reinforce the trunk}
{3304}{}{Install "gravity plates"}
{3305}{}{Decrease power consumption with fuel regulator}
{3306}{}{Increase the speed of the at the biker in Battle Mountain}
{3307}{}{Restore headlights}
{3308}{}{Take a random fellow traveler to Vegas}
