{100}{}{You see the Jovial Joe.}
{101}{}{You see a very funny bald guy with the eternal smile and protruding teeth. If not for clothing, you would've thought that he is crazy.}
{102}{}{ }

#Dialogue
{109}{}{A new face in our venue? Make yourself comfortable! There is no such bar in the world, where you can sit for long without buying some alcohol and getting drunk. And for this we do our job! Choose, what would you like?}
{110}{}{Well, what do you want for a drink?}
{111}{}{Show me what you have.}
{112}{}{Nothing, I'm leaving.}
{113}{}{I'd like to complain about your waitress. She was rude to me!}
{114}{}{Ow! Come on! She's a cool old lady. Everyone here is crazy about her, and you will soon love her too. Relax!}
{115}{}{W-well, whatever...}
{116}{}{That's all? Buddy, you will die from hunger like this! Ha-ha-ha!}

#Women's replics:
{118}{}{I'd like to complain about your waitress. She was rude to me!}
{119}{}{That's all? Buddy, you will die from hunger like this! Ha-ha-ha!}

#Post-games bonus:
{120}{}{Ho-Ho! Look who has come to our city! It's nice to see, mister, that you don't forget us! You here for long?}
{121}{}{Ho-Ho! Look who has come to our city! It's nice to see, miss, that you don't forget us! You here for long?}
{122}{}{No, I ran in for a couple of minutes, to guzzle a mug of beer, Joe.}
{123}{}{No, I ran in for a couple of minutes, to guzzle a mug of beer, Joe.}
{124}{}{I'll drop in from time to time. Bye now!}
{125}{}{Yes, [vigorously shakes head] I understand! To hit the road again, to save the Wasteland from the dirty bastards! I'm so happy, that such valiant people like you still visit our region occasionally.}
{126}{}{Sure, the world is not without good people...}
{127}{}{Sure. And I also would like to make you pleased. [Pulls out a pair of glasses, and a moldy bottle] You wouldn't believe how old this drink is. It's a great luck to come across something like this in the Wasteland. But lucky me, I snatched one box for a reasonable price. However, it is almost all consumed already. Here, I want to drink to your well being.}
{128}{}{[More]}
{129}{}{[You spend some time listening to fascinating stories of Joe with a bottle of delicious whiskey] ... so that's how we got rid of that Deathclaw. Scary, right?}
{130}{}{Oh, Joe, everything is much simpler with those Deathclaws. But I think you already know this, if you met the thing face to face. Hmm?}
{131}{}{Uh... Yeah! Uh... Of Course. Of course, I know all about them. [looks at the bottle]... Um, you know... Hell, I admire you so much that I will give you this whole bottle. Here you go!}
{132}{}{Wow, thanks for the rarity, Joe! I'll see you around. Bye.}

#Inquire about the city
{140}{}{I want to ask you about the city.}
{141}{}{I want to buy a drink for everyone in here to introduce myself.}
{142}{}{Not right now, buddy. Did you met working trains here somewhere?}

{143}{}{Sorry, but taking your reputation into account, it won't help you.}
{144}{}{Damn!}
{145}{}{A great way to introduce yourself to the city! Put out 200 bucks, and everyone here will find out who you really are.}
{146}{}{Here is the money. Hey, guys, beer's on me! For everyone!}
{147}{}{Uh, actually I want to ask you about the city.}
{148}{}{Not today. Bye.}
{149}{}{A good idea to start with, but trust me - in this city you won't build reputation only by buying everyone a beer. Start small.}
{150}{}{Thanks for the tip, Joe.}

{151}{}{Oh, that's the reason why I'm wearing out the seat of my pants here everyday!}

{152}{}{Who runs this place?}
{153}{}{Is this place run by the law?}
{154}{}{This gallows - is it often empty?}
{155}{}{Where can I patch up myself or my equipment?}
{156}{}{Can you tell me more about the area?}
{157}{}{Why there are so many caravaneers here?}
{158}{}{Okay, let's quit the chatter.}
{159}{}{I see. Can I ask another question?}

{160}{}{I guess it's the Sheriff. He has everyone's asses on a string - thus no skunk will dare to show its faces in here any more. Oh, yeah.}
{161}{}{The Sheriff is the law. All will be as he says.}
{162}{}{Come back around afternoon, when it's not too dark yet. Usually at that time they feed the new victims of the show to the audience. Funny guys they are.}
{163}{}{Well, you can get a kick out of vending machines or buy some grub, the Kwok brothers across the street sell equipment and the technician from the Nuka-Cola factory will help you to cope with broken inventory. In the North, in front of the Sheriff's office, there is a pharmacist, however, lately there's almost nothing left to buy from him. Also you may stay in the hotel when the weakness is about to floor you.}
{164}{}{[he sighs, apparently, he's tired of this question] Oh, God... It's the business center. If you need some equipment or want to relax - come here. The factory of Nuka-Cola is to the East, and further in that direction is the canyon of the wastewater. To the North there is the residential area where the Sheriff's office is located. Overall, it is better not to wander around because of radiation, wild dogs, acid geckos... and many other hostile abominations.}
{165}{}{In recent years Salt Lake has attracted more entrepreneurs. The situation is, you know, the high time to line your pockets with cash. Those who realized this in time have bent the entire potential of the city to their interests. That's why the city still has what to offer to other settlements.}

{166}{}{[suddenly everyone around you falls silent and turns to you] What are you talking about?}
{167}{}{Uh, I say, do you have a working train? That can actually move, you know?}
{168}{}{[Joe looks around the audience, his smile is draining from the face, becoming similar to a grin] No, we just have piles of rusty metal.}
{169}{}{But you do have a railroad, right?}
{170}{}{So?}
{171}{}{So tell me, where is the railway station with trains.}
{172}{}{[lowers his voice, the smile slipping from his nervous face] Look, even I rarely dare to joke on this subject... don't go there. And stop speaking about it.}
{173}{}{Hey! Take it easy!}
{174}{}{Looks like you asked a wrong question. Something is wrong here...}

{175}{}{Who is this guy that was hanging out at the entrance?}
{176}{}{Incorrigible Ned? A walking bag full of guts. I would not have used a work of such a sloven if only he didn't ask so little for his service. And I don't mind saving a few coins. Ha!}

#Recipe of the peanut paste
{177}{}{}
{178}{}{You gain 75 experience points for the successful application of the trading skill.}
{179}{}{Forget it, I gotta go.}
{180}{}{What kind of peanut paste you have in stock?}
{181}{}{Paste? Ah, yes, the paste of the Vocas nuts. The result of my culinary research. As you can see, a failed one.}
{182}{}{Why failed?}
{183}{}{Because this muck was too hard and acidic for the stomach. The technician from the factory had been buying it to use as a cleaning agent against rust, but then he started to cook it himself when learned the recipe. Shit...}
{184}{}{Interesting. Would you share the recipe?}
{185}{}{Hey, you're that guardian angel who walks around the town and restores justice? No problem then - here's the recipe and I won't take a buck in exchange!}
{186}{}{Great.}
{187}{}{Why would I share it with a stranger?}

{188}{}{Well, I can pay.}
{189}{}{I'll say, you're a cheapskate. Goodbye.}
{190}{}{You know, I don't need it that much. I can live without your recipes. Bye.}

{191}{}{Hey, good idea! 100 bucks and the recipe is yours. What do you say?}
{192}{}{Well, I can pay.}
{193}{}{75, and not a dollar more.}
{194}{}{Okay, I'll buy it.}
{195}{}{Well, okay. The truth is yours - who else I will be able to sell this recipe to? I agree to 75.}
{196}{}{Never mind about the recipe. Let's talk about something else.}
{197}{}{Don't step on my aching corns! I'm already giving it almost for free!}
{198}{}{Wow, you'll really pay for it? Wonderful! So... [writes the recipe on a piece of paper] don't lose it. If you have problems accessing a kitchen you can use a simple bonfire for it.}
{199}{}{All right.}

####################################################################
#
# THE JOVIAL JOE SHOW
#
# Author: Aleksandr Agafontsev aka Kerb
#
####################################################################

# Markers:
# GGG -- Joe phrases
# TTT -- replics over the "strange person"

####################################################################
# Story number 1. About The Ghost Train.
####################################################################

{300}{GGG}{By the way, I didn't tell you about the Ghost Train yet? So...}

{301}{}{You didn't tell? You didn't for the hundredth time, you wanted to say?}
{302}{}{One more word and there will be the story about the Ghost Bartender!}
{303}{}{Don not remember it in vain!}
{304}{}{Don't listen them, Joe! Fire away, buddy!}

{310}{GGG}{...So!!! Most people believe that it collects souls and sends them straight to hell...}

{311}{}{Then I need to book a ticket for my old lady!}
{312}{}{ }
{313}{}{Soul? Then you have nothing to fear about. Ha ha ha!}
{314}{}{ }

{320}{GGG}{...Their poisoned with beer brains are not smart enough to come up with other versions...}

{321}{}{Since when the piss you serve here became beer?}
{322}{}{By the way, that beer is yours, Joe!}
{323}{}{Do not generalize! My brain was eaten out by my wench...}
{324}{}{ }

{330}{GGG}{Quiet there! Ehm... So, the true story of the train is known to a few...}

{331}{}{A few? And you are, like, the chosen one?}
{332}{}{Few survived the local booze! While this story was heard by everyone.}
{333}{}{ }
{334}{}{Are there other secrets protected by this talking pumpkin of yours?}

{340}{GGG}{Look, you... I'm telling you about things no one else will!}

{341}{}{Seriously, Joe! I haven't heard such stories as yours even in the mental hospital!}
{342}{}{Your talent shines brighter than your own bald head, my friend! I'm all ears!}
{343}{}{ }
{344}{}{ }

{345}{TTT}{::discreetly pulls out a gun from the belt::}

{350}{GGG}{That's okay, you'll remember it later! So - actually the train has one master and one purpose...}

{351}{}{To smear your guts over the rails!}
{352}{}{To bring proper booze and whores in here!!! Yeah, Joe! Keep it up!}
{353}{}{ }
{354}{}{ }

{355}{TTT}{::takes the trigger lock off::}

{360}{GGG}{This is... Well, it's like with the ghouls! It is believed that they have been exposed to radiation, right?}
{370}{GGG}{But you know who they really are? They are aliens who were disguised as humans even before the war!}

{371}{}{No, Joe. It's the humans who are disguised as them. Ha ha!}
{372}{}{He is on fire! Joe, you're the best!}
{373}{}{Radiation? They just pumped selves with your beer and didn't manage to take a pee on time!}
{374}{}{ }

{380}{GGG}{...and it's *them* who started the war, in order to walk around without disguise! Sounds about right!}

{381}{}{::scratches his head with mouth agape::}
{382}{}{So you've managed to put psycho in your evening mug eventually?}
{383}{}{You completely went off the rails, Joe!}
{384}{}{You, like, started this with a train...}
{385}{}{Uh...}

{390}{GGG}{Train? What train? The one where I met Elvis?}

{391}{}{Yeah. Who was also an alien, hasn't died, and flew home. Forget it!}
{392}{}{Rather go get us the best of your beer...}
{393}{}{ }
{394}{}{ }

{395}{TTT}{::removes the weapon and takes his beer. Strange.::}

####################################################################
# Story number 2. "Joe the Invisible".
####################################################################

{400}{GGG}{All right, boys! I decided...}

{401}{}{To tell another tall tale? Then you'd better have decided to hang yourself!}
{402}{}{Decided to finally replace the piss in the mugs with something real?}
{403}{}{Or to buy yourself a brain?}
{404}{}{ }

{410}{GGG}{No-no... I, like,... I won't tell you anything anymore...}

{411}{}{Holy crap, I must be high and dreaming!}
{412}{}{And I then will cease chasing the skirts!}
{413}{}{You'll switch to chasing men? Or you decided to hook up with a brahmin?}
{414}{}{What did you say!?}

{420}{GGG} {B-... be quiet! You're constantly interrupting me anyway... Looks like you don't like all this...}

{421}{}{Come on, Joe! You speak nicely! If only you could connect the words into the sentences that would make sense...}
{422}{}{ }
{423}{}{ }
{424}{}{I like it, Joe! I was hanging out in a madhouse once, so listening to you evokes nostalgia!}

{430}{GGG}{So I decided to mark this moment with a splash of new beer! Top grade thing!}
{440}{GGG}{The beer called "Joe the Invisible"! Like... yeah...}
{450}{GGG}{Only... You have to chip in, just 2 bucks a pint.}

{451}{}{Good beer, silent Joe... fuck this, where am I?! Put me back into the "Tin angel"!}
{452}{}{If the level of brahmin piss in it is 5 percent lower than in this, it's already good...}
{453}{}{What piss?! All the drinks Joe serves are made of fresh rat feces!}
{454}{}{Hey! Let's chip in, everybody!}

{460}{GGG}{::silence::}

{461}{}{Uh... Joe?}
{462}{}{Where's the beer?}
{463}{}{Raging thirst!}
{464}{}{I don't see any beer yet!}

{470}{GGG}{Well, like,.. That's Joe the Invisible! For it being visible only in menu...}

{471}{}{I don't understand...}
{472}{}{Joe is trying to be funny?}
{473}{}{Whoa... That's what we usually do, no?}
{474}{}{Where is this world heading...}

####################################################################
# Story number 3. About the book.
####################################################################

{480}{GGG}{Hey, guys. I wrote something here...}

{481}{}{Wrote? You put an X instead of a signature!}
{482}{}{ }
{483}{}{What did you write? A last will? When is the funeral?}
{484}{}{ }

{490}{GGG}{No, I'm serious!}
{500}{GGG}{I wrote a book... well, only a title for now...}
{510}{GGG}{However, I lost that piece...}

{511}{}{In the same magical land where they replaced your coconut with a pumpkin, huh?}
{512}{}{Lost? Rather wiped your ass in a toilet with it...}
{513}{}{Hey, quit it! Come on, Joe! Keep it up.}
{514}{}{ }

{520}{GGG}{Well... It's about one man who fell into the bunker... and there is a full...}

{521}{}{Bag of brahmin dung?}
{522}{}{Bunker of hookers and booze! Yes, Joe! More!!!}
{523}{}{ }
{524}{}{ }

{530}{GGG}{No, no... a full tank filled with some stuff... what was it...}
{540}{GGG}{Ah! Forced amplification gainer! FAG! I came up with the name myself!}

{541}{}{Yeah, who could doubt that...}
{542}{}{You'd better come up with the idea of how to get some good hooch...}
{543}{}{ }
{544}{}{ }

{550}{GGG}{So he falls in there! And turns into something of an abomination, a hybrid, kinda like a roach crossbred with a scorpion...}
{560}{GGG}{...additionally plunged in a puddle of rad-wastes.}

{561}{}{Hey, exactly like my mother-in-law!}
{562}{}{Oh, I wouldn't mind be crossbred with someone...}
{563}{}{Shut your mouth, you horny pig! Going to go to my wife again?}
{564}{}{ }

{570}{GGG}{Quiet there!..}
{580}{GGG}{...And thus he starts catching people and turning them into huge green monsters!}
{590}{GGG}{Others become telepathic interacting with FAG! And he wants to turn the entire world into these things!}
{600}{GGG}{And he calls himself... what was the word? The Lord? No, that sounds stupid. Ah, forget it! So...}

{601}{}{What bastard gave him drugs?}
{602}{}{Hey, Joe! Pour me a handful of thing you are smoking!}
{603}{}{And then, like, a tough hero appears and slaughters your Lord? Ha-ha-ha!}
{604}{}{Yeah, even stupid comedians of the twentieth century would never come up with such a story.}

{610}{GGG} {Ah! So, how was it?}

{611}{}{ }
{612}{}{ }
{613}{}{ }
{614}{}{Oh, I had a friend, doctor Moreau, First, he would have laughed hard, and then unscrewed your pumpkin from the shoulders for such anti-scientific crap... FAG, jeez...}

{620}{GGG}{I have seen one such guy myself! He just glanced - and crawled into my head!}

{621}{}{... and was stunned by the amount of empty space.}
{622}{}{Cut it already, Joe. Better pour me another Bloody Mary...}
{623}{}{ }
{624}{}{ }

####################################################################
# Story number 4. About The Great War.
####################################################################

{630}{GGG}{G-... Guys! Look how the life has changed since before the War!}

{631}{}{Yeah. Normal booze and whores became harder to get.}
{632}{}{Oh! Good morning, Mr. Genius!}
{633}{}{Your pumpkin decided to write a thesis in philosophy?}
{634}{}{Yeah, then it was forbidden to lynch bartenders for the diluted drinks! Just saying.}

{640}{GGG}{No... I'm not talking about that. I'm talking about all the new things that have appeared...}
{650}{GGG}{Rad-Scorpions... Rad-cockroaches... By the way, why...}

{651}{}{If you'll ask, what's so RAD about them, I will shoot you!}
{652}{}{Someone should get executed for this stupid joke already!}
{653}{}{I think I've heard it already somewhere...}
{654}{}{Better to add the "rad" prefix to your swipes. One doesn't even need a flashlight after drinking your 'beer'!}

{660}{GGG}{Hmm...! I wanted to tell you about the vampire ghoul from Pennsylvania!}

{661}{}{From Transylvania, you weirdo! Count... uh... Glad the Inhaler!}
{662}{}{I wanted to tell you about the vampire-from-the-bar-sucking-money-from-us.}
{663}{}{ }
{664}{}{Joe, bring it on! You're my only replacement for a TV.}

{670}{GGG}{Do not interrupt! So... there once was a good man.}
{680}{GGG}{And he had in his life two moments of joy: work and relax.}
{690}{GGG}{He worked at the blood bank, was, like, collecting blood of the people and was happy that it helps other people.}
{700}{GGG}{And he loved to relax in the bar across the street...}

{701}{}{...And the bar was called "Tin angel"}
{702}{}{...One day, instead of another bottle of shitty beer, he drank the blood of the bartender. The end.}
{703}{}{ }
{704}{}{Don't interrupt! He's about to make a gag, as usual.}

{710}{GGG}{After the war erupted the bank was closed, and then his town was smashed... with, like... a strike!}
{720}{GGG}{And he still sat there, after the closing. And turned into a ghoul! And his brains from the radiation got, like, jammed!}

{721}{}{Got it! Then he disguised himself as the bartender and opened a bar called "Tin angel"!}
{722}{}{You've guessed that because of what Joe said about the brain?}
{723}{}{Uh, I have a sudden urge to go home...}
{724}{}{ }

{730}{GGG}{Uh... No. He forgot what he was doing. Only remembered that he needed blood to help people.}
{740}{GGG}{And that he, for some reason, used to go to some bar. So, he concluded, that the blood was the reason he was going there.}
{750}{GGG}{But how the bar was called, he could not remember!}
{760}{GGG}{And now he wanders the earth, looking for bars, enters them at night, kills the visitors and drains their blood!}
{770}{GGG}{What doesn't fit he finishes off drinking it himself...}
{780}{GGG}{And he will stop only when he finds that bar... which since 2077 lies in ruins.}

{781}{}{So he won't find his bar? That sucks...}
{782}{}{Not funny and not scary. Uh... It's not going to get dark very soon, right?}
{783}{}{Guys, Pennsylvania is far away from Nevada, yes? Right?}
{784}{}{I have the swipes Joe serving instead of blood anyway. Let's have another one!}

{785}{TTT}{For the poor guy from Pennsylvania!}

####################################################################
# Story number 5. About Halloween.
####################################################################

{790}{GGG}{Guys! Will we celebrate the Halloween?}

{791}{}{You bet! It's the only reason for a pumpkin of yours to be here.}
{792}{}{Glad that you keep it empty, there is space for a pair of candles to insert.}
{793}{}{Only if you, in honor of the holiday, will be pouring the drinks for free!}
{794}{}{For drinking the swill like this it's him who should pay us instead!}

{800}{GGG}{Yes! I'll pour! I'll roll out the barrel of my best beer...}

{801}{}{And why are you so kind?}
{802}{}{And in honor of pumpkines... uh... pumpkins, we'll have a party! With booze and hookers!}
{803}{}{Hey! Why are you so whooping, you sack of hormones?!}
{804}{}{ }

{810}{GGG}{No, no. I just have cherished memories of Halloween...}

{811}{}{About that psychopath from Sparks, who at night of Halloween skinned two, butchered four with the "Ripper", released the guts of another two, and tortured three for the whole day, and then buried them on the city outskirts?}
{812}{}{Uh... About those three, they told they went missing... You're not from Sparks?}
{813}{}{You were also looking for batteries... Not for the "Ripper" by chance? No?}
{814}{}{Hey! Shut the hell up!}

{820}{GGG}{No! It's the memories of my wife...}
{830}{GGG}{Oh! She had a very special way to blow my mind, or should I say, to eat my brain.}
{840}{GGG}{Compared to her, you guys are just kids...}

{841}{}{Brain? You once had a brain?}
{842}{}{It was fair, old boy! You fucked her, she fucked your brain!}
{843}{}{Share your grief and it will be doubled! Tell it, buddy!}
{844}{}{ }

{850}{GGG}{But... But I still loved her.}
{860}{GGG}{In the Halloween 20 years ago we met for the last time.}
{870}{GGG}{It hurts to recall my last words: "Get out of here to your mom in Iowa, you walking cemetery of iguanas-on-a-stick!"...}
{880}{GGG}{I thought we will reconcile the next day as it usually was...}
{890}{GGG}{... and she went to collect the herbs and got lost...}
{900}{GGG}{But she certainly wanted to make my favorite gecko's thigh with the condiment of Brock flowers...}

{901}{}{Ha ha! Mrs. pumpkin ran away from Mr. pumpkin!}
{902}{}{Shut up, asshole!}
{903}{}{Come on, Joe, don't let your nose drip.}
{904}{}{Roll out you barrel now! I'm paying! And be sure to share a drink with us!}

####################################################################
# Story number 6. About the bald head (sample).
# Author: Aleksandr Poshelyuzhin
####################################################################

{910}{GGG}{Many of you are wondering, what did I do to my hair.}
{920}{GGG}{So. I once came to the Nuka-Cola factory...}

{921}{}{What, Joe, got tired of your old job?}
{922}{}{Why did you go there? It's much better here with us.}
{923}{}{If you would go for a batch of proper beer instead, it would be more interesting.}
{924}{}{Don't listen to these idiots! What happened next?}

{930}{GGG}{I came to the factory and said...}

{931}{}{Oh! Joe can speak! Unbelievable!}
{932}{}{Oh, come on! Enough already!}
{933}{}{You're telling this for the hundredth time...}
{934}{}{I knew you got bald because of Cola. You need to know the limits, Joe!}

{940}{GGG}{No, wait! Let me tell you...}
{950}{GGG}{So I came to the factory and said: "And where do you get the water for Cola?"}
{960}{GGG}{And they are all arrogantly to me: "Oh, we get it out of the sewer". "What?! - I tell them - It's toxic!"}
{970}{GGG}{And they said, "You think your swipes are cleaner?"}
{980}{GGG}{Well, I did not believe: "Show me!" - I said.}
{990}{GGG}{They led me to the sewers, and there's...}

{991}{}{What? Rats? The mutants?}
{992}{}{Joe pooped his pants and fled. Admit it already.}
{993}{}{And there, in the pipes, the Cola runs instead of urine. He he.}
{994}{}{And the beggar sits there and fills the bottles with urine.}

{995}{TTT}{What's the reason you've dragged yourself to the sewers!? You've completely lost your mind...}

{1000}{GGG}{No, no, wait, let me finish!}
{1010}{GGG}{And there's... there's... Oh, I can't!!!}
{1020}{GGG}{*laughs so hard that will soon fall on the floor laughing*}
{1030}{GGG}{And there's... Oh, hell...}
{1040}{GGG}{*wipes a tear away* Uh...}
{1050}{GGG}{No, I'll better serve the Rotgut to the fifth table.}
