{100}{}{You see Niskigvan Ruffled Feathers.}
{101}{}{You see a tanned, middle-aged Native American with a stoned look in his eyes.}

#Плавающие сообщения
{110}{}{Now that was unnecessary...}
{111}{}{Sorry, maybe later...}

#########################################################
#
#           The tale about mouse
#
#########################################################

{112}{}{Once upon a time, children, there was a little mouse.}
{113}{}{He was the youngest mouse out of all his brothers and sisters.}
{114}{}{One day, he heard a noise he'd never heard before. "What was that noise?" he asked.}
{115}{}{"What noise?" said the other mice. "Tend to your garden. There is no noise."}
{116}{}{But this mouse was curious. He went on a journey find the noise.}
{117}{}{He met a frog. The frog said, "You hear the Great River flowing. I will take you there."}
{118}{}{They traveled together to the Great River. When they got there, the frog said...}
{119}{}{"Jump as high as you can, and you'll see the Great Mountains!"}
{120}{}{And so the mouse did. He jumped so high, he saw the Great Mountains! But they were very far away.}
{121}{}{The mouse was curious about the mountains. He knew he couldn't rest until he saw them up close.}
{122}{}{So the mouse traveled through the Great Plains to get to the Great Mountains.}
{123}{}{Suddenly, he saw a bison lying in the plains. He was strong and mighty.}
{124}{}{"Brother bison!" said the mouse. "Please take me to the Great Mountains!"}
{125}{}{"But I can't," said the bison. "I've died. Only the eye of a mouse can save me."}
{126}{}{"An eye?" the mouse asked. "Here, if it will save you, take mine!"}
{127}{}{The bison took the gift and came back to life. In gratitude, he took the mouse to the Great Mountains.}
{128}{}{At the base of the Great Mountains, the mouse saw a wolf hiding in the bush. Still, silent, thinking.}
{129}{}{"Brother wolf!" said the mouse. "Please help me climb the Great Mountains!" But the wolf didn't speak.}
{130}{}{The mouse knew the wolf had died, and so gave him his other eye.}
{131}{}{And so the wolf came back to life. In gratitude, he took the mouse to the very heart of the Great Mountains.}
{132}{}{Now the little mouse was all alone in the heart of Great Mountains, unable, even for a moment, to witness their beauty.}
{133}{}{Suddenly he saw, in blur... The soil... The water... But everything became so distant...}
{134}{}{And someone spoke to him. "Hello, brother, you have joined our flock. Fly with us. Fly with us, brother eagle!"}
{135}{}{Well, children? Did you like it? If you're good, I'll tell you another story later...}

#########################################################
#
#                 Начало диалога
#
#########################################################

{200}{}{What do you need, outsider?}
{201}{}{I need healing.}
{202}{}{I need medication.}
{203}{}{Your healing stuff actually work, are you serious?}
{204}{}{Sorry, what are you doing?}
{205}{}{I found your lost backpack.}

{206}{}{Nothing.}
{207}{}{Do you know where the radio station is?}

#########################################################
#
#                    Лечение героя
#
#########################################################

{250}{}{Let's see. [he examines you, mumbling to himself] Yes, yes...I can heal you.}
{251}{}{Let's see. [he examines you, mumbling to himself] Yes, yes...I can heal you, but you'll have to pay me 100 of your dollars.}
{252}{}{Heal me!}
{253}{}{Here's the money. Now heal me!}
{254}{}{But I don't have that much money. Are you really just going to let me suffer?}
{255}{}{Never mind, then. It'll heal on its own. In the meantime, I have other questions.}
{256}{}{Actually, I don't need anything after all.}

{257}{}{I am the healer of my tribe. I should not have to say anything else.}
{258}{}{I'm not asking, I'm ordering! Heal me, or else!}
{259}{}{Fine, here's the money! Just heal me!}
{260}{}{[he smiles smugly] In the past, a raider came to torture me. Now, a raider pleads for my mercy. It's funny, don't you think?}
{261}{}{Shut up and heal me!}
{262}{}{That's interesting. I'll go think about it.}
{263}{}{You would harm my body to make me heal yours? [he shakes his head] Wisdom has made you foolish, outsider, if this is what your journeys have taught you.}
{264}{}{Fine, here's 100 bucks! Heal me already!}
{265}{}{Fuck this. I'll deal with it on my own. Thanks for nothing.}
{266}{}{I did as much as I could.}

{267}{}{In the past, a raider came to torture me. Now, he asks for a favor. No, outsider. Seek help from your own people.}
{268}{}{I won't forget this, old man!}
{269}{}{Fine, I'll ask my people at the camp.}

#########################################################
#
#          Производство медикаментов и
#          получение достижения "Знахарь"
#
#########################################################

#Производство
{300}{}{We can't share what little we have, outsider. But I can mix medicine for you if you bring me the components.}
{301}{}{What do you need to make healing powder?}
{302}{}{What do you need to make an antidote?}
{303}{}{I have another question.}
{304}{}{That's all.}

{305}{}{Make one.}
{306}{}{Make two.}
{307}{}{Make three.}
{308}{}{Make five.}
{309}{}{Make ten.}

{310}{}{Xander root, a broc flower, and 25 of your dollars.}
{311}{}{The tail of a radscorpion and 25 of your dollars.}

{312}{}{Done.}
{313}{}{I have another question.}
{314}{}{That's all.}

{315}{}{Can you make medicine for an infection?}
{316}{}{[he raises his eyebrows] That's a complicated task, outsider. I'll need xander root, a broc flower, two bunches of nightshade berries and 250 of your dollars.}

#Достижение Знахарь
{350}{}{I will never forget what you did for Makkon. No reward would be enough, but I'd be honored to teach you everything I know.}
{351}{}{You've done so much for our tribe. I'd be honored to teach you everything I know. May it help you on your journey.}
{352}{}{Can you teach me how to make herbal medicine?}
{353}{}{Of course. You won't need healers anymore. You'll know how to use the gifts of nature to heal yourself.}
{354}{}{Great! Teach me, oh great healer!}
{355}{}{I don't have time right now. Can we do it later?}
{356}{}{When you're ready, return here and I will teach you.}
{357}{}{Actually, I can find some time. Teach me, oh great healer!}
{358}{}{I'll come back.}

#########################################################
#
#          Расспросы о радиостанции
#
#########################################################

{360}{}{Radio...? No, I do not know.}
{361}{}{You're lying! Show me where it is, now!}
{362}{}{Another question, then.}
{363}{}{Fine, but I’ll come back.}

{364}{}{You come into my home, a place of peace and healing, and threatening me?! How dare you?!}
{365}{}{Have it your way. I'll go through your villagers one by one until somebody shows me where it is. You'll have plenty of people giving your "place of healing" its proper respect then.}
{366}{}{Woah, woah, sorry. I just got a little excited. But don't you really know where the station is?}
{367}{}{This is pointless. I'm leaving.}

{368}{}{No.}
{369}{}{Fine.}
{370}{}{No, wait! I'll show you the radio station. Just don't hurt anyone!}
{371}{}{Now we're talking! Get moving, old man.}

#########################################################
#
#          Расспросы о врачебном опыте
#
#########################################################

#Обмен врачебным опытом
{400}{}{Yes. The Ruler of Life gives us food and water. By living in harmony with our environment and being aware of the gifts we are given, we have everything we need to survive.}
{401}{}{You can't possibly treat advanced diseases and injuries with herbs and water.}
{402}{}{Couldn't you do more if you had better tools, though?}
{403}{}{I see. I want to ask something else.}
{404}{}{That's all I wanted.}

{405}{}{I don't expect a city person like you to understand. We, Cheyenne, have lived this way for many years, whether you choose to believe it or not.}
{406}{}{Hmm. What gifts does nature provide, then?}
{407}{}{What techniques do you use?}
{408}{}{And does it work?}
{409}{}{And how healthy are the Cheyenne?}
{410}{}{Why don't you use pre-war medicine?}

{411}{}{We use roots, herbs, mushrooms, and mouse feces.}
{412}{}{What roots?}
{413}{}{What kind of herbs?}
{414}{}{Mushrooms?}
{415}{}{Mouse feces?! You're kidding!}
{416}{}{How all of this can help with healing?}
{417}{}{I have other questions.}

{418}{}{Many roots, especially xander root, can be smoked, rubbed into the skin, or drunk as a tea.}
{419}{}{How do they help?}
{420}{}{What else do you use?}

{421}{}{Our magical healing powder tastes bitter, but is poisonous to the evil spirits that take root in the body.}
{422}{}{You mean it has antimicrobial properties? Okay, what about your other medicine?}
{423}{}{I'll keep that in mind. What else do you use?}

{424}{}{Broc flowers, and other plant life.}
{425}{}{Spicy upon the tongue, but miraculous taste of potion relieves the heat of the body and speeds its recovery.}
{426}{}{You mean they can break a fever? It sounds like they have antibiotic properties. What about your other medicine?}

{427}{}{Mushrooms, which hide from the eye of the seeker in the dark corners of the wasteland.}
{428}{}{Mushroom's glow lights the path to healing, guiding the spirit through its trials, and thus relieving the body's suffering.}
{429}{}{It sounds like they have hallucinogenic and pain-relieving properties. Tell me about your other medicine.}

{430}{}{I don't kid about the Heavenly Mother's gifts, outsider. These mouse feces contain the life energy of the Earth itself.}
{431}{}{Not every mouse feces can heal. Only those mice that live in caves and have never gone outside are blessed by the Heavenly Mother and can aid the body's healing process.}
{432}{}{Hmm...it sounds like something connected to the mice's diet. Their feces probably contain minerals that boost the body's metabolism. Okay, what about your other medicine?}
{433}{}{Only those gifted by the Heavenly Mother can make medicine from these components. Others are doomed to drink poison.}
{434}{}{Right. Tell me one more time about those components.}
{440}{}{The ritual of healing is never the same. Sometimes, a tea of herbs and roots is all someone needs to recover. Other times, I must fight for one's life with everything the Heavenly Mother has given me - pipes, spells, potions, and of course, the skill of my hands.}
{441}{}{I see.}
{442}{}{All healing is a battle in its own way. That's why it is often a trial of pain and screaming...but with bravery and perseverance, even the strongest evil spirits will leave the body.}
{443}{}{Right.}
{444}{}{We are strong, even in old age, when outsiders are wracked and weakened by the spirits infesting them. The Cheyenne people will outlive all others in the wasteland.}
{445}{}{Well, if you say so.}

{446}{}{Humanity had forgotten what the Heavenly Mother taught us. Pre-war medicine could chase away evil spirits, but did not strengthen the body, so those spirits were always replaced by others - often stronger.}
{447}{}{I see.}
{448}{}{That's not true. There was a lot of medicine and treatments used before the war. Some of it could be useful to you.}
{449}{}{Outsiders' medicine has never helped us. Don't try to convince me on blind faith it will now.}
{450}{}{Hmm. If I knew more about pharmaceutics, maybe I could convince you. Maybe later.}
{451}{}{I'm an expert in medical field. I could explain it to you, if you share your knowledges with me in return.}

{452}{}{Hmm... [he regards you curiously] The Heavenly Mother always taught us to seek new knowledge.}
{453}{}{So, let's make ourself comfortable?}
{454}{}{Of course. I'd be happy to share with you.}
{455}{}{Let's get started, then!}
{456}{}{Not now.}

{457}{}{Exchanging medical techniques with Niskigvan has increased your first aid skill by 5%.}

#########################################################
#
#          Принадлежности лекаря
#
#########################################################

{460}{}{[he grumbles under his breath] I have had to do without some of the Heavenly Mother's gifts recently. It is hard to work my craft with nothing but knives and spoons.}
{461}{}{The fertile earth provides all we need, if we have the wisdom to see it.}
{462}{}{We have what we need. Thank you, again.}

{463}{}{What happened?}
{464}{}{That's sad to hear. Let's talk about something else.}
{465}{}{In that case, I'll let you concentrate on your work. Goodbye.}

{466}{}{You're welcome. Can you answer some more questions?}
{467}{}{No problem. See you later.}
{468}{}{Right.}

{469}{}{It's hard to collect herbs and roots without my backpack. All of my supplies were in there.}
{470}{}{What happened to it?}
{471}{}{Let’s talk about something else.}
{472}{}{I won't make you dwell on it. I'll leave you alone.}

{473}{}{One of the raiders took it when I was away from the village. It will be a long time before we can spare the leather for a new one, and it will take even longer to replace the tools I kept in it. Healing will be difficult for some time.}
{474}{}{What if I get your backpack for you?}
{475}{}{[he looks at you with an unsure expression] These are dangerous men, outsider. To approach them is to risk death, unless you are one of them.}
{476}{}{Don't worry about me. You'd be amazed how often I take deadly risks.}
{477}{}{Never mind, then.}
{478}{}{If you hope for a reward, I have hardly anything to give, and even less that would interest an outsider like yourself.}
{479}{}{Well, I want to help anyway. Maybe it will change your view on outsiders.}
{480}{}{I'm not a charity. Forget it.}
{481}{}{Then I would be very gracious for your kindness.}
{482}{}{Do you know where to look for that raider?}
{483}{}{Okay, but I have more questions first.}
{484}{}{I'll be back with your stuff.}

{485}{}{The raiders hideout is not far from here, to the north. The one who took my backpack is named Furymaker.}
{486}{}{No doubt the Ruler of Life sent you! Thank you, outsider! Such generosity is rare in our times - rare and precious. For as long as you live, I will heal your injuries without payment.}
{487}{}{That's great, but all this generosity really works up an appetite...}
{488}{}{Aw, it was nothing. You're welcome.}

{490}{}{Of course! Wait here. I will bring you some sandwiches from Omakaki.}
{491}{}{[Wait.]}

#########################################################
#
#          После отказа в лечении Маконса
#
#########################################################

{500}{}{The chief didn't allow me to treat Makkon!}
{501}{}{Ogima's word is final.}
{502}{}{Ogima's word is final. I will not act against him.}
{503}{}{But what do we do now?!}

{504}{}{It is done, outsider. Forget it and go peacefully.}
{505}{}{Are you serious?! Walk away, just like that?}
{506}{}{Fine, I will. But you will regret this!}

{507}{}{[he leans forward, looking into your eyes] Is outsider's heart weights with grief, like my own?}
{508}{}{Yes!}
{509}{}{And he wants only to help, without asking anything in return?}
{510}{}{Of course!}

{511}{}{[he sighs] The chief is right. There is too much darkness in your heart, outsider, to place Makkon's life in your hands.}
{512}{}{[Leave.]}
{513}{}{[he gives a very long, troubled sigh] Chief Ogima...wise as he is, he is only a man like myself. Sometimes, even he is wrong...and I know more of healing than him, don't I?}
{514}{}{Exactly! What can I do to prove you can trust me?}
{515}{}{Too often outsiders claim to have skills they do not. Just last month, a man came from the east. He promised us rain, but could only show us the clouds.}
{516}{}{You want to test my knowledge?}

{517}{}{Have you changed your mind about examining my healing skills?}
{518}{}{Chief Ogima has forbade me to treat Makkon.}

#########################################################
#
#          Перед лечением Маконса
#
#########################################################

{550}{}{What happened to that boy in the corner?}

{551}{}{Poor Makkon. His legs were crushed in a landslide. For so long, I've tried to save him, but his legs are in constant pain and he's fallen into a fever for three months. Even the Heavenly Mother's gifts cannot produce miracles. I won't give up on him, but feel that he will die soon. Everyone in the village grieves for him.}
{552}{}{If your, uh, mother isn't enough, maybe more advanced medicine can save him. Can I help?}
{553}{}{I hope that all works out. See you.}
{554}{}{Hmm... [he frowns] Go talk to Ogima. I cannot make this decision. I am too close to this boy, and I cannot allow my heart to think instead of my head.}
{555}{}{I'll talk to him. But first, another question.}
{556}{}{I'll go talk to him then.}

{557}{}{I'd like to help you with treating that injured boy. Your chief gave me permission.}

{558}{}{You're serious? You want to help?! This is a rarity in our times. [he pauses, then his brow furrows] I would love to see you heal this boy, but if even my skill is not enough...are you *sure* you can handle it?}
{559}{}{I’m sure.}
{560}{}{Then I would like to test your skills first. I have never seen you work before. Shall we begin?}
{561}{}{No problem. Let's get started.}
{562}{}{I’m a little tired right now. Maybe later?}

#########################################################
#
#          Тест героя перед лечением Маконса
#
#########################################################

{600}{}{We will test your skills, outsider. [he straightens his posture and peers keenly into your eyes] I will ask questions, and you will answer.}
{601}{}{I'm ready.}
{602}{}{[he pulls his robe aside to show a scar located to the left of, and slightly below, his navel] When I was shot here, what did the bullet hit?}
{603}{}{Your lungs.}
{604}{}{Your colon.}
{605}{}{Your bladder.}
{606}{}{Your small intestine.}
{607}{}{Your penis.}

{610}{}{Hmm. And why wasn't the injury lethal?}
{611}{}{All of your bones remained intact.}
{612}{}{Your central nervous system remained intact.}
{613}{}{Your belly contains a lot of water, which stopped the bullet.}
{614}{}{The heat of the bullet cauterized the injury.}
{615}{}{It didn't hit any vital organs.}

{620}{}{Hmm. And what does the small intestine do for the body?}
{621}{}{It processes blood.}
{622}{}{It holds urine.}
{623}{}{It holds feces.}
{624}{}{It sucks the water out of food.}
{625}{}{It digests food.}

{630}{}{Hmm. And how long does it take for such an injury to heal?}
{631}{}{A few hours.}
{632}{}{A few days.}
{633}{}{A few weeks.}
{634}{}{A year.}

{640}{}{Hmm. How should we treat this injury, so that it is not infected with evil spirits?}
{641}{}{Wash it out with water from the well.}
{642}{}{Wash it out with alcohol, such as booze.}
{643}{}{Sear it with fire or heated metal.}
{644}{}{Lick it.}
{645}{}{Nothing, the heat of the bullet already cauterized the wound.}

{650}{}{Hmm. Some herbs help the body restore injured flesh quickly, but they all have a side effect. What is the side effect of powder made from xander root and broc flowers?}
{651}{}{It weakens your strength.}
{652}{}{It reduces your endurance.}
{653}{}{It clouds your perception.}
{654}{}{It slows your agility.}
{655}{}{There is the risk of becoming addicted.}

{660}{}{Hmm. Some pre-war medicine is very addictive. If the addicted person doesn't get it regularly, they suffer. Can this addiction be treated?}
{661}{}{Yes. Go long enough without another dose and the addiction will eventually fade.}
{662}{}{Yes. Another type of medicine can remove the addiction.}
{663}{}{Yes. Conducting a rite of purification with special smoke will remove the cravings.}
{664}{}{No. The burden will last forever.}

{665}{}{What now?}
{666}{}{[Continue.]}

#Оценка знаний (теоретическая подготовка)
{667}{}{That is all. [he smiles and his eyes glint with excitement] Your knowledge of healing is incredible, outsider! Perhaps, it's you, who should be testing me! Together, I think we have the wisdom to treat Makkon.}
{668}{}{That is all. [he smiles] You know much of healing, outsider. I know I can trust you.}
{669}{}{That is all. [he frowns] Makkon's condition is very complicated, outsider, and I don't think you have the knowledge to treat it correctly. But perhaps you have skills in other areas.}
{670}{}{[he throws up his hands] There's no point in continuing this. You don't know anything! How can you call yourself a healer? I can't risk you treating Makkon. I...I forbid it!}
{671}{}{[he crosses his arms] Experience has told me that knowledge is not enough. Omakaki was my helper once, and while she learned much of herbs, roots, and plants, she could not make a simple potion. Show me your skills on this dummy, so I may see them in practice.}
{672}{}{Sometimes, the Ruler of Life deprives a person's skills in one area, but grants them something else in exchange. Gekek had a brother who could not tell the difference between an iguana and a gecko, but could throw a spear through its eye from fifty paces. Show me your skills on this dummy, so I may see them in practice.}

{673}{}{Niskigvan analyzed your medical skills by watching you work on the dummy.}
{674}{}{Now, I will know the swiftness of your hands. You must have skillful fingers to work with soft or damaged flesh. Here is a gecko skin and needle. Drive the needle through the dots I have left for you.}
{675}{}{[Niskigvan carefully appraises the speed, accuracy, caution, and confidence of your needlework] Hmm. Now, I will know the sharpness of your eyes. Here are two glasses of water. In one, you have water from the well, and in the other, carefully purified water. Tell me which is the purer water.}
{676}{}{[Choose.]}
{677}{}{Hmm. Now, I will know the stamina of your heart. The operation may take several hours, and it will be exhausting work. Do some sit-ups, and then, I will listen to the speed of your heart.}
{678}{}{Fine, let's do this. [begin sit-ups]}

#Оценка умений и способностей (практическая подготовка)
{679}{}{[after a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm...you are remarkably fit and talented, outsider! You make the old man jealous!}
{680}{}{[after a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm...yes, this should be enough. You are strong and skilled enough for this surgery, outsider.}
{681}{}{[after a few minutes, Niskigvan grabs your wrist and measures your heart rate] Hmm...I am not sure you have the strength for this operation, outsider. I had hoped for more from someone so much younger than me. But with both of us there, perhaps it will be enough.}
{682}{}{[after a few minutes, Niskigvan shakes his head] Stop, stop. Your kind spirit cannot make up for the weakness of your body, outsider. If I let you perform this surgery, you'll kill the boy, and maybe yourself! I'm sorry, but...I must forbid you from treating Makkon.}
{683}{}{Finally, the last test. I have here a pet mouse. She is very sensitive and can easily determine the difference between filthy and pure. I will place some seed in your hands, and we will see if she eats it.}

{684}{}{[the mouse runs from you without even trying to eat the food in your hands] Hmm...I think there are evil spirits within you. Poison, sickness, or even something darker. Anyway, I'm ready to make my decision.}
{685}{}{[the mouse cautiously sniffs at the seed in your hands, then starts to eat] An animal cannot be tricked! I'm ready to make my decision!}

#Итоговая оценка (по сумме теории/практики и с учетом проверки мышью)
{686}{}{I had no idea the Heavenly Mother granted such blessings to the people of the city! I will be honored to assist you during the operation.}
{687}{}{You did well, outsider! I have no doubts now. Together, we should be able to heal Makkon.}
{688}{}{I believe I can trust you, outsider. You will be able to assist me in the operation.}
{689}{}{You are a great healer, outsider! I will be honored to have your help during the operation! But you should be careful - animals know things that we people do not. If there are evil spirits within you, do not allow them to grow too strong, or it will end badly for you.}
{690}{}{You did well, outsider. It is a shame that the mouse smelled uncleanliness on your hands, but I still think you can handle the operation.}
{691}{}{I had reasons to trust you, outsider, but animals know things that we people do not. I do not know what my mouse feared in you, but I cannot allow you to treat Makkon. I... forbid it.}

{692}{}{Anything else?}
{693}{}{Remember that time will not wait for you, outsider. A few more months without treatment, and the boy will die. Rest for now, and when you're ready to discuss the operation, come to me.}
{694}{}{That’s it! I’m leaving.}
{695}{}{[Exit.]}

{696}{}{For passing the test with flying colors, you earn }
{697}{}{For your great performance on the test, you earn }
{698}{}{For passing the test, you earn }
{699}{}{ experience points.}

#########################################################
#
#          Обсуждение лечения Маконса
#
#########################################################

{700}{}{Let's discuss Makkon's operation.}
{701}{}{[he sighs] The time has come. What should we do?}
{702}{}{First, we'll have to drain the pus and reduce the inflammation. We'll have to make him bleed and clean the injury.}
{703}{}{[he nods] Yes, yes...we need clean water and a sharp knife. But how will he endure it? He is so young...}
{704}{}{Yes, the boy needs anesthesia. Pre-war chems would be best, but if you don't trust them, we can give him alcohol or herbs.}
{705}{}{Yes...my healing powder can give him respite in the world of dreams. But you bring your chems, too. When the time comes, we'll decide what is best. What else?}
{706}{}{We'll need strong hands to set his broken bones, and forceps or pliers to remove any bone fragments under the skin.}
{707}{}{Yes, that's right. And after that?}
{708}{}{We'll have to stitch and bandage his injuries and splint his broken bones.}
{709}{}{Bandages? In the cities, they are stored in boxes marked with a red cross. You will probably know better than me where to get them.}
{710}{}{Yes, in first aid kits. But after the operation is complete, the boy will need constant care and lot of bed rest. He'll need medication to deal with his fever and something to stimulate the growth of cells.}
{711}{}{Yes, I will prepare healing powder from xander root and broc flowers. It will speed his recovery.}
{712}{}{I can also bring stimpaks. Don't worry, they're harmless. A stimpak contains natural components, but heals much more effective, than healing powder}
{713}{}{Good, I will leave that to you.}
{714}{}{Remind me, what's the full list of things we need?}
{715}{}{We need 1) clean water; 2) healing powder, painkillers, or alcohol; 3) a sharp knife; 4) forceps or pliers; 5) a first aid kit; and 6) healing powder or stimpaks.}
{716}{}{When you have everything, come back here.}
{717}{}{I'll be back.}

{718}{}{About Makkon - what do we need?}
{719}{}{Don’t forget anything. We need: }
{720}{}{Right.}

#########################################################
#
#          Операция
#
#########################################################

{800}{}{I'm ready to perform the operation on Makkon.}

{801}{}{[he takes a deep breath, then nods] It is time. You have a sharp knife?}
{802}{}{Right here.}
{803}{}{Er...no.}
{804}{}{How will we do this without a knife? What were you thinking? You can't be so careless with Makkon's life!}
{805}{}{Good. Then we shall begin.}
{806}{}{[Begin.]}
{807}{}{No, wait, I forgot something. I'll be right back.}

{808}{}{[Niskigvan's hands shake slightly, but he looks determined] We must make sure Makkon does not awake during the operation. What will we use?}
{809}{}{Let's use your healing powder.}
{810}{}{I have painkillers in this doctor's bag.}
{811}{}{I have painkillers in this first aid kit.}

{812}{}{But what if they're dangerous? Where were they kept? What if they've spoiled?}
{813}{}{Fine, use your traditional medicine.}
{814}{}{These painkillers don't expire and have no side effect. Read the bottle, it's a clean product! Besides, i've used such ones myself.}
{815}{}{Good. See, the boy's eyes are already closing...he is in the world of dreams now, and don't feel pain. Let's prepare his wounds. [Niskigvan's hands tremble as he removes the bandages from Makkon's feet, but his movements are confident] What will we use to prevent infection? Those spirits are very cunning...}
{816}{}{Clean water.}
{817}{}{The bottle of booze. The alcohol will sterilize his wounds.}
{818}{}{I have some rotgut here. The alcohol will sterilize his wounds.}
{819}{}{We'll have to risk using well water.}
{820}{}{No! [he shakes his head, frowning] I will prepare the water. I have a herbal infusion that will clean it.}
{821}{}{What's next?}
{822}{}{Everything is ready. It's time to take care of his bones. Where's the knife? It should also be sterilized. Did you get pliers, or something like?}
{823}{}{Use these thin pliers. They'll be perfect.}
{824}{}{No, sorry.}
{825}{}{These too must be cleaned...there. Hold his legs here, while I remove the loose fragments...}
{826}{}{Hmm. That is not good. Fortunately I have some pre-war tweezers here. A poor tool for such a delicate operation, but there is nothing else. Hold his legs while I remove the fragments...}
{827}{}{[you spend half an hour treating Makkon's wounds and removing small bone fragments from his legs]}
{828}{}{We must wash out the pus. We'll have to open the wounds. [You gently drain the pus from Makkon's injured flesh]}
{829}{}{We must wash out the pus. We'll have to open the wounds. Why are you standing around? We cannot afford to lose any time! Hold his legs while I release the pus.}
{830}{}{The tissue is clean. There is no turning back now. Now we need to set the bones. [he takes a deep breath] If we damage the tissue, he will be as bad as when we started. Let us begin.}
{831}{}{[you clean the wounds] Now we must stitch the wounds shut, or at least, bandage them tightly.}
{832}{}{I have gauze and bandages in this doctor's bag.}
{833}{}{I have gauze and bandages in this first aid kit.}
{834}{}{I have nothing like that. Maybe we can use a gecko skin?}

{835}{}{[Niskigvan blinks rapidly as sweat runs into his eyes] Now we have to put a splint. I have wooden poles and some cloth to tie them. [You and Niskigvan carefully splint Makkon's injured legs. Makkon slowly starts to come around, moaning softly.] Quiet, Bear Cub. Stay strong. We are almost done.}

{836}{}{[Finally, you tie the last bandage. Niskigvan stands, his hands shaking with fatigue.] The operation is complete. Makkon's body must heal. We must decide how to rehabilitate him.}
{837}{}{Bed rest and plenty of food. He'll need to devote all of his strength to healing.}
{838}{}{He'll need to be treated with healing powder tomorrow to speed his recovery.}
{839}{}{Here's a stimpak. It makes cells grow faster. Inject it into his leg tomorrow .}
{840}{}{Here's two stimpaks. Inject one into each leg tomorrow. It will prompt cell growth and speed the recovery process.}
{841}{}{[The healer's face is pale and slick with sweat. He washes his hands and steps outside for some fresh air.]}
{842}{}{[Go get some fresh air too.]}

{843}{}{I feel sick...}

{844}{}{I have an old painkiller.}

{860}{}{I have a switchblade.}
{861}{}{I have an old kitchen knife.}
{862}{}{I have a throwing knife.}
{863}{}{I have a sharp combat knife.}
{864}{}{I have a straight razor.}
{865}{}{Knives for surgery? Barbaric! Use this scalpel. It's designed specifically for this purpose.}

#Сообщения в консоль после операции:
{850}{}{You earn 1000 experience points for assisting Niskigvan as he treated Makkon's crippling injuries. You and Niskigvan both learned something new.}
{851}{}{You earn 2000 experience points for helping Niskigvan treat Makkon's crippling injuries. You and Niskigvan both learned something new.}
{852}{}{You earn 3000 experience points for treating Makkon's crippling injuries. You and Niskigvan both learned something new.}
{853}{}{You earn 5000 experience points for your miraculous healing. You and Niskigvan both learned something new.}

#########################################################
#
#          Устаревшая часть диалога (not used, old version)
#
#########################################################

{2146}{}{Я направляюсь на базу рейдеров по заказу Огимы Черного Облака. Можете что-нибудь посоветовать?}
{2149}{}{Вы можете сделать сильный яд? На базе рейдеров есть бак с питьевой водой. Если отравить им воду...}

#Про отравление воды рейдерам
{2178}{}{Небесная Мать не для того наградила меня даром знахаря! Я лечу, а не гублю людей. Ну, и если честно... я просто не умею делать никакого яда. Если вы готовы взять на себя такую ношу - вам прямая дорога в город Нью-Рино.}
{2179}{}{А это где?}
{2180}{}{Там делают яд? А кто именно?}
{2181}{}{А вы откуда знаете про Рино?}
{2182}{}{Ясно. Еще вопрос.}
{2183}{}{Это бесовский город недалеко на юго-западе. Лучше там не появляться. Но с другой стороны, в округе ничего столь же большого нет. Я отмечу его вам на карте, но предупреждаю - будьте там осторожны и не заходите в глухие кварталы.}
{2184}{}{Я не помню имен. И едва ли у них есть имена. Поспрашивайте в городских заведениях. Такие слова как "я хочу отравить" или "мне нужно убить человека" в Нью-Рино слышатся чаще, чем приветствия.}
{2185}{}{Никто из нашего племени не прошел столько дорог и не встретил стольких людей, чтобы сравниться в этом со мной. Это долго объяснять - история шайеннов насчитывает много лет. Приходилось о многом заботиться, и наши боги вели меня... Видите тот оросительный водосборник напротив хижины Огимы? Он сделан не без помощи чудесных технологий Нью-Рино.}
{2186}{}{Ясно. Ну, мне пора к рейдерам.}

#########################################################
#
#             Женские реплики
#
#########################################################

{1205}{}{I found your lost backpack.}
{1300}{}{We can't share what little we have, outsider. But I can mix medicine for you if you bring me the components.}
{1366}{}{Woah, woah, sorry. I just got a little excited. But you really don't know where the station is?}
{1370}{}{No, wait! I'll show you the radio station. Just don't hurt anyone!}
{1450}{}{Hmm. If I knew more about medicine, maybe I could convince you. Maybe later.}
{1451}{}{You won't need blind faith. I'm an expert in medicine. I could explain it to you.}
{1480}{}{I'm not a charity. Forget it.}
{1486}{}{No doubt the Ruler of Life sent you! Thank you, outsider! Such generosity is rare in our times - rare and precious. For as long as you live, I will heal your injuries without payment.}
{1504}{}{It is done, outsider. Forget it and go peacefully.}
{1507}{}{[he leans forward, looking into your eyes] The outsider's heart is heavy with grief, like my own?}
{1509}{}{And she wants only to help, without asking anything in return?}
{1557}{}{I'd like to help that injured boy. Your chief gave me permission.}
{1559}{}{I’m sure.}
{1562}{}{I’m a little tired right now. Maybe later?}
{1704}{}{Yes, the boy needs anesthesia. Pre-war chems would be best, but if you don't trust them, we can give him alcohol or herbs.}
{1800}{}{I'm ready to perform the operation on Makkon.}
{1802}{}{Right here.}
{1804}{}{How will we do this without a knife? What were you thinking? You can't be so careless with Makkon's life!}
{1807}{}{No, wait, I forgot something. I'll be right back.}
